### ISSUE TITLE
Logs are setted to stderr

### ISSUE THREAD

**Issue by iahazat** [datarobot/batch-scoring#149]
Hi, 

Actually the batch_scoring commands write the logs on stderr, can you please change it to stdout.

Waiting for your answers,

Thank you for your comprehension,

Best regards,

**Comment by farafarafara** [comment]
Hello,

Sorry it took that long to get back to you. We have discussed your ask and decided not to write logs to stdout since logs are not a regular output of the program. There is a way to redirect stderr output to stdout, you just have to add `2>&1` to your command. 

Example:
batch_scoring --host=https://hostname.datarobot.com --user="email@company.com" --datarobot_key=<key> --api_token=<token> --out=pred.csv <project_id> <model_id> file_to_score.csv 2>&1

It is also possible to redirect the output to the file, for this change `2>&1` to `2> out.txt`

Please let me know if that clears things up.

Best regards,
Valeriia
